#!/bin/bash
# Build Chrome and Firefox Artifacts for ProxyAssistant Extension
# Usage: ./script/build.sh [version]

set -e

# Get version from argument or use "dev"
VERSION=${1:-"dev"}
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="${PROJECT_DIR}/src"
BUILD_DIR="${PROJECT_DIR}/build"

echo "=========================================="
echo "Building ProxyAssistant - v${VERSION}"
echo "=========================================="

# Cleanup previous build
echo "Cleaning up build directory..."
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"

# ---------------- Chrome Build ----------------
echo "------------------------------------------"
echo "Building Chrome Artifacts..."

# Prepare source for Chrome
echo "Preparing Chrome source..."
cp -r "${SRC_DIR}" "${BUILD_DIR}/src-chrome"

# Use Chrome manifest
cp "${BUILD_DIR}/src-chrome/manifest_chrome.json" "${BUILD_DIR}/src-chrome/manifest.json"

# Remove extra manifest files (we use unified worker.js)
rm -f "${BUILD_DIR}/src-chrome/manifest_chrome.json" \
      "${BUILD_DIR}/src-chrome/manifest_firefox.json"

# Build ZIP
echo "Creating Chrome ZIP..."
cd "${BUILD_DIR}/src-chrome"
zip -q -r "../ProxyAssistant_${VERSION}_chrome.zip" .
cd "${PROJECT_DIR}"

# Build TAR.GZ
echo "Creating Chrome TAR.GZ..."
tar -czvf "${BUILD_DIR}/ProxyAssistant_${VERSION}_chrome.tar.gz" -C "${BUILD_DIR}/src-chrome" . > /dev/null

# Cleanup Chrome source
rm -rf "${BUILD_DIR}/src-chrome"

# ---------------- Firefox Build ----------------
echo "------------------------------------------"
echo "Building Firefox Artifacts..."

# Prepare source for Firefox
echo "Preparing Firefox source..."
cp -r "${SRC_DIR}" "${BUILD_DIR}/src-firefox"

# Use Firefox manifest
cp "${BUILD_DIR}/src-firefox/manifest_firefox.json" "${BUILD_DIR}/src-firefox/manifest.json"

# Remove extra manifest files (we use unified worker.js)
rm -f "${BUILD_DIR}/src-firefox/manifest_chrome.json" \
      "${BUILD_DIR}/src-firefox/manifest_firefox.json"

# Build ZIP (for manual install/review)
echo "Creating Firefox ZIP..."
cd "${BUILD_DIR}/src-firefox"
zip -q -r "../ProxyAssistant_${VERSION}_firefox.zip" .
cd "${PROJECT_DIR}"

# Build TAR.GZ
echo "Creating Firefox TAR.GZ..."
tar -czvf "${BUILD_DIR}/ProxyAssistant_${VERSION}_firefox.tar.gz" -C "${BUILD_DIR}/src-firefox" . > /dev/null

# Build XPI using web-ext
if command -v web-ext >/dev/null 2>&1; then
    echo "Building Firefox XPI with web-ext..."
    
    # Run web-ext
    # Note: web-ext outputs to artifacts-dir. If it outputs a zip, we rename it.
    
    mkdir -p "${BUILD_DIR}/dist"
    web-ext build --source-dir "${BUILD_DIR}/src-firefox" --artifacts-dir "${BUILD_DIR}/dist" --overwrite-dest > /dev/null
    
    # Rename generated zip to xpi and move to BUILD_DIR
    XPI_FILE=$(ls "${BUILD_DIR}/dist"/*.zip 2>/dev/null | head -1)
    if [ -n "$XPI_FILE" ]; then
        mv "$XPI_FILE" "${BUILD_DIR}/ProxyAssistant_${VERSION}_firefox.xpi"
        echo "Generated: ProxyAssistant_${VERSION}_firefox.xpi"
    else 
        echo "Warning: No XPI generated by web-ext"
    fi
    rm -rf "${BUILD_DIR}/dist"
else
    echo "Warning: web-ext not found. Skipping XPI build."
    echo "To install: npm install -g web-ext"
fi

# Cleanup Firefox source
rm -rf "${BUILD_DIR}/src-firefox"

echo "=========================================="
echo "Build completed successfully!"
echo "Output files in ${BUILD_DIR}:"
ls -lh "${BUILD_DIR}" | grep "ProxyAssistant"
echo "=========================================="
